import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  image: {
    width: "100%",
    flex: 1,
    resizeMode: "cover",
  },
  text: {
    textAlign: "center",
    color: "black",
    fontSize: 25,
  },
  Headers: {
    alignItems: "center",
    justifyContent: "center",
    height: "150",
    backgroundColor: "white",
  },
  trektext: {
    fontSize: 25,
  },
  button1: {
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    height: 170,
    width: 180,
    rigth: 70,
    left: 10,
    borderRadius: 10,
    top: 365,
    padding: 3,
  },
  button2: {
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    height: 170,
    width: 180,
    rigth: 80,
    left: 200,
    borderRadius: 10,
    top: 368,
    padding: 1,
  },
  button3: {
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    height: 170,
    width: 180,
    rigth: 80,
    left: 200,
    borderRadius: 10,
    top: 5,
    padding: 1,
  },
  button4: {
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    height: 170,
    width: 180,
    rigth: 80,
    left: 10,
    borderRadius: 10,
    padding: 1,
    top: 8,
  },
  imgbtn: {
    width: 100,
    height: 100,
  },
  imgbtn1: {
    width: 100,
    height: 100,
  },
  imgbtn2: {
    width: 100,
    height: 100,
  },
  imgbtn3: {
    width: 100,
    height: 100,
  },
  imgbtn4: {
    width: 100,
    height: 100,
  },
});
